// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UpdatetestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void updatetest() {
    driver.get("http://localhost/Assignment/admin2.php");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.name("id")).click();
    driver.findElement(By.name("id")).click();
    driver.findElement(By.name("id")).sendKeys("0000");
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) > input")).sendKeys("test 01");
    driver.findElement(By.name("des")).click();
    driver.findElement(By.name("dead")).click();
    driver.findElement(By.name("dead")).click();
    {
      WebElement element = driver.findElement(By.name("dead"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("dead")).sendKeys("30.10.2020");
    driver.findElement(By.cssSelector("tr:nth-child(5) .button")).click();
  }
}
